// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as JSONService from "./jsonservice.js";
import * as WindowManager from "./windowmanager.js";
export {
    JSONService,
    WindowManager
};
