// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * FormatJSON prettifies JSON with 2-space indentation while preserving large numbers
 * preserveOrder: currently ignored due to Go's map limitations - both modes produce the same output
 * @param {string} input
 * @param {boolean} preserveOrder
 * @returns {$CancellablePromise<string>}
 */
export function FormatJSON(input, preserveOrder) {
    return $Call.ByID(99097422, input, preserveOrder);
}

/**
 * MinifyJSON removes all whitespace from JSON while preserving large numbers
 * @param {string} input
 * @returns {$CancellablePromise<string>}
 */
export function MinifyJSON(input) {
    return $Call.ByID(3538244587, input);
}

/**
 * ValidateJSON checks if JSON is valid and returns error details
 * @param {string} input
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function ValidateJSON(input) {
    return $Call.ByID(1989899627, input);
}
