// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * IsAlwaysOnTop returns the current always-on-top state
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAlwaysOnTop() {
    return $Call.ByID(163322224);
}

/**
 * OpenNewWindow creates a new window instance with the same size as current window
 * @returns {$CancellablePromise<void>}
 */
export function OpenNewWindow() {
    return $Call.ByID(10882929);
}

/**
 * ToggleAlwaysOnTop toggles the always-on-top state of all windows
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleAlwaysOnTop() {
    return $Call.ByID(1078084336);
}
